<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<link rel="shortcut icon" type="image/ico" href="/images/favicon.ico">
	<meta charset="utf-8">
	<?php 
		//Title will be "[Current Page Title - ] Imago Dei College", e.g. "Home - Imago Dei College", or, if none is set, just "Imago Dei College"
		$this->headTitle()->append("Imago Dei College");
		$this->headTitle()->setSeparator(" - ");
		echo $this->headTitle()
	?>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


	<!-- Le styles -->
	<?php 
		$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.css'); 
		$this->headLink()->appendStylesheet($this->basePath() . '/css/global.css'); 
		echo $this->headLink(); 
	?>
	<!-- <link href="/css/bootstrap-responsive.css" rel="stylesheet"> -->

	<!-- scripts -->
	<?php 
		$this->headScript()->prependFile("https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"); 
		$this->headScript()->appendFile($this->basePath() . '/js/bootstrap.min.js'); 
		//$this->headScript()->appendFile($this->basePath() . '/js/bootstrap.js'); 
		$this->headScript()->appendFile($this->basePath() . '/js/idc.js'); 
		echo $this->headScript();
	?>
</head>

<body>
	<div class="container">
		<?php echo $this->content; ?>
	</div>
	<script type="text/javascript">
	<?php
		$controller = explode('\\', ($this->currentController));
		$action = ucfirst(stripslashes($this->currentAction));
		echo '$().idc("init' . $controller[2] . $action . '");';
	?>
	</script>
	<?php echo $this->inlineScript(); ?>
</body>
</html>





