<div class="row">
	<div class="span12">

		<div class="hero-unit">
			<div>
				<h1>
					Imago Dei College
				</h1>
				<p>
				connects Portland college students with one another to engage with Christian truth and interact with today's most challenging questions. This is a place for Christians and for those who are not. All are welcome to come, hang out, listen, and even jump into the conversation if desired.
				</p>
			</div>
		</div>
	</div>
</div>

<div class="row">


	<div class="span12">


		<div id="myCarousel" class="carousel slide">
			<!-- Carousel items -->
			<div class="carousel-inner">
				<div class="active item">
					<img src="/images/students-blur.png">
				</div>
				<div class="item"> <img src="/images/portland-bridge.png"></div>
				<div class="item"> <img src="/images/portlandia-statue.png"></div>
			</div>
			<!-- Carousel nav -->
			<a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>
			<a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>

		</div>

	</div>
</div>

<div class="container">
	<div class="row">
		<div class="span12">
			<h1 style="text-align: center;">Why College?</h1>
		</div>
	</div>
	<div class="row alert alert-block" style="margin-left: 0px;">



		<p>Transfer credits. Campus housing. Meal plans. Study groups. Course schedules. Labs. Great roommates. Horrible roommates. Tuition payments. Part-time jobs. Getting fired from part-time jobs. Desperately taking any part-time, minimum-wage job you can find, even if it makes you work until 4 a.m.... Can someone say "transitional"?</p>

		<p>Yeah, you can scream it. You don't have time or money or well-developed non-Facebook social networks, and you're feeling it. This time of constant change makes it tough to genuinely connect with anybody, never mind establish and build real life-giving friendships.  But we want to know you and we want you to know us. We are compelled to build a community that not only supports college students by helping them "get through" these crazy years—we want to collectively thrive.</p> 
	</div>

</div>

<a name="mentoring"></a><div class="page-header">
</div>
<div class="row">
	<div class="span6">
		<div><h2>
				Mentoring
			</h2>
			<p>
			We are developing a network of older men and women who truly want to mentor and disciple college-age people. One goal will be to connect students not only with those mentors but also with the life of Imago Dei Community as a whole, including its home communities, church ministries, men's and women's forums and other places that will help them fight the loneliness of autonomy and live the lives they were built for—lives in real community.
			</p>
		</div>
	</div>
	<div class="span5 alert alert-info alert-block" style="margin-top: 20px;">
		<div class="row" style="margin-top:20px;">
			<div class="span3">
				<h3>
					Become a Mentor
				</h3>
			</div>
			<div class="span2">
				<a style="margin-top: 15px; text-align: center;" class="btn btn-success" href="become-a-mentor.html">
					<strong>Mentor Application</strong>

				</a>
			</div>

		</div>
		<div class="row">
			<div class="span3" style="margin-bottom: 20px;">
				<h3>
					Find a Mentor
				</h3>
			</div>
			<div class="span2"> 
				<a style="margin-top: 15px; text-align: center;" class="btn btn-warning" href="receive-a-mentor.html">
					<strong>Student Sign Up</strong>
				</a>
			</div>

		</div>
	</div>

</div>


<div class="row">
	<div class="page-header">
	</div>
	<div class="span12">
		<h1 style="text-align: center;">What does an average night look like?</h1>
	</div>

	<div class="span11 alert alert-block">
		<p>We rendezvous every Friday night, from 7-9:30 p.m. to, at times, engage in a brief presentation of theology, philosophy, or biblical teaching from professors, pastors and other speakers. At other times, share meals, hang out and talk, watch and discuss movies, and so on. We're big on switching things up a lot.</p>

		<p>We also encourage you to stay late with us.  We'll keep the lights on until 10:00 and the world is your oyster.  Take avantage of the gym for a game of dodgeball or ask nicely and maybe we'll even throw a log in the fire.  It's during this downtime that we have the opportunity to build spiritual friendships, even if it means taking a kickball to the face.</p>
	</div>
</div>

<hr>
<div>
	<p>For questions about college group, contact our Pastoral Intern/Point Leader: 

	Patrick Wilson - patrick@imagodeicommunity.com - (503) 313-3342</p>

	<p>To become a leader or mentor, contact our Pastor of Students:

	Ben Tertin - ben.tertin@imagodeicommunity.com - (503) 780-0784</p>
</div>
<br><br><br><br><br><br><br><br><br><br>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js">
</script>
<script src="/js/bootstrap.js">
</script>
